/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited.
// It is regenerated by `next` on dev/build; committed so typecheck works pre-build.
